### PR TITLE
toying with cursor

### PR DESCRIPTION
**Pull request by willpuckett**
experimenting with issue [#29](https://github.com/oliver-oloughlin/kvdex/issues/29). This PR changes the return shape of most (all?) of the functions that use kv.list to include a cursor property for pagination.

### CODE REVIEW

**Comment by oliver-oloughlin** [comment]
Approving the PR and merging into main. 

**Note:**
The changes made here make the existing list operations slightly more cumbersome to use as the result needs to be destructured/captured, even if you simply want to handle all documetns in the given collection. I'm unsure if this should just be left as it is, or maybe if every ``xxxMany()`` function should be accompanied by an ``xxxAll`` function with more restrictive options, so to offer simpler alternatives for the use cases that need to handle every document in the collection.

**Comment by willpuckett** [comment]
I definitely prefer your ideaof adding an all variant rather than changing getMany... I don't like the destructuring either it makes the api more clunky... I considered using Object.addProperty to tuck the cursor onto the array onto something like .__cursor, but apparently it's not a best practice and TypeScript doesn't seem to like it. 
Hope your other projects are going well!

**Comment by willpuckett** [comment]
I think naming the new variants with a "paged" prefix or suffix would make the most sense...

**Comment by oliver-oloughlin** [comment]
I'm sort of torn on the idea. On one hand it would be nice to have the simplified, non-paging versions. At the same time, it seems redundant to have two slightly different versions of methods for doing basically the same thing. The new variants still allow for a relatively simple way of getting/deleting/etc. all documents in a collection. I'll think on it for a bit.

Btw, I did remove support for paging for the "findBySecondaryIndex" method. This is because I couldn't see any practical way of actually doing it, as it uses multiple iterators in a single call, making a simple cursor attribute non-functional. I also think that it doesn't make sense to support it for the use case of looking up indexed documents.

**Pull request merged**
